# Generated by Django 4.2.6 on 2023-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
    ]
